### ISSUE TITLE
https://lodestar-lightclient.chainsafe.io is not using updated latest proof endpoint

### ISSUE THREAD

**Issue by philknows** [ChainSafe/eth2-light-client-demo#58]
**Describe the bug**

Currently our [browser light client](https://lodestar-lightclient.chainsafe.io/) is not able to fetch state because of it using the old proof endpoint.

**Expected behavior**

Should be able to fetch latest proof.

**Screenshots**

![Screenshot_2023-01-04_at_10 44 10](https://user-images.githubusercontent.com/58080811/211070734-302ec25b-5da0-4f7f-9fde-f362fe040929.png)

**Comment by jeluard** [comment]
@philknows  Is this still relevant? I can't reproduce this.

**Comment by philknows** [comment]
Doesn't look applicable anymore, thanks for the ping. Closing.
